# Generated by Django 4.1.7 on 2023-04-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barril',
            fields=[
                ('num_barril', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('volumen', models.IntegerField(default=50, null=True)),
                ('fecha', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('vendedor', models.CharField(max_length=30, null=True)),
                ('lista_precios', models.CharField(choices=[('Precio1', 'Precio 1'), ('Precio2', 'Precio 2'), ('Precio3', 'Precio 3')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estilo', models.CharField(max_length=20, null=True)),
                ('precio1', models.FloatField(blank=True, null=True)),
                ('precio2', models.FloatField(blank=True, null=True)),
                ('precio3', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lote', models.CharField(max_length=20, null=True)),
                ('fecha_lote', models.DateField(null=True)),
                ('estilo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.estilo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoBarril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('En Fabrica', 'En Fabrica'), ('En Cliente', 'En Cliente')], max_length=20)),
                ('fecha_cambio', models.DateField(null=True)),
                ('num_barril', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.barril')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='enFabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lote')),
                ('num_barril', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.barril')),
            ],
        ),
        migrations.CreateModel(
            name='enCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lote')),
                ('num_barril', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.barril')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Embarrilado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lote')),
                ('num_barril', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.barril')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='barril',
            name='estado_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barriles', to='accounts.estadobarril'),
        ),
        migrations.AddField(
            model_name='barril',
            name='estilo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.estilo'),
        ),
        migrations.AddField(
            model_name='barril',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lote'),
        ),
        migrations.AddField(
            model_name='barril',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cliente'),
        ),
    ]
