# Generated by Django 4.1.7 on 2023-04-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_barril_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='Fabrica', max_length=200, null=True),
        ),
    ]
