# Generated by Django 4.1.7 on 2023-03-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_order_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='costumer',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='num_barril',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AddField(
            model_name='order',
            name='num_pedido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cliente',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='estilo',
            field=models.CharField(choices=[('Golden', 'Golden'), ('Honey', 'Honey'), ('Irish Red', 'Irish Red'), ('Ipa Argenta', 'Ipa Argenta'), ('Caramel Ipa', 'Caramel Ipa')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lote',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='num_barril',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ubicacion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='volumen',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
