# Generated by Django 4.1.7 on 2023-03-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_name_customer_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lista_precios',
            field=models.CharField(choices=[('Precio 1', 'Precio 1'), ('Precio 2', 'Precio 2'), ('Precio 3', 'Precio 3')], max_length=30, null=True),
        ),
    ]
