# Generated by Django 4.1.7 on 2023-03-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_lista_precios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='vendedor',
        ),
    ]
