# Generated by Django 4.1.7 on 2023-03-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_email_customer_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='estilo',
            field=models.CharField(blank=True, choices=[('Golden', 'Golden'), ('Honey', 'Honey'), ('Irish Red', 'Irish Red'), ('Ipa Argenta', 'Ipa Argenta'), ('Caramel Ipa', 'Caramel Ipa')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lote',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
