# Generated by Django 4.1.7 on 2023-03-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_product_cliente_alter_product_estilo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Barril',
        ),
    ]
