# Generated by Django 4.1.7 on 2023-03-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_product_barril'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Embarrilado',
        ),
    ]
