# Generated by Django 4.1.7 on 2023-03-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_order_embarrilado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarrilado',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='embarrilado',
            name='num_pedido',
        ),
        migrations.RemoveField(
            model_name='embarrilado',
            name='status',
        ),
    ]
