# Generated by Django 4.1.7 on 2023-03-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_embarrilado_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarrilado',
            name='ubicacion',
            field=models.CharField(default='Fabrica', max_length=20, null=True),
        ),
    ]
