# Generated by Django 4.1.7 on 2023-03-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_embarrilado_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estilo', models.CharField(max_length=20, null=True)),
                ('precio1', models.FloatField(blank=True, null=True)),
                ('precio2', models.FloatField(blank=True, null=True)),
                ('precio3', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
