# Generated by Django 4.1.7 on 2023-03-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_estilo_delete_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Cliente',
        ),
    ]
