# Generated by Django 4.1.7 on 2023-03-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_customer_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='lista_precios',
            field=models.CharField(choices=[('Precio1', 'Precio 1'), ('Precio2', 'Precio 2'), ('Precio3', 'Precio 3')], max_length=30, null=True),
        ),
    ]
