# Generated by Django 4.1.7 on 2023-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_cliente_lista_precios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarrilado',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
