# Generated by Django 4.1.7 on 2023-03-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_embarrilado_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
