# Generated by Django 4.1.7 on 2023-03-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_cliente_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='date_created',
        ),
    ]
