# Generated by Django 4.1.7 on 2023-03-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fecha_lote',
            field=models.DateField(null=True),
        ),
    ]
