# Generated by Django 4.1.7 on 2023-03-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_lote_fecha_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barril',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
