# Generated by Django 4.1.7 on 2023-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_barril_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barril',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
