# Generated by Django 4.1.7 on 2023-03-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_barril_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barril',
            name='date_created',
        ),
    ]
