# Generated by Django 4.1.7 on 2023-03-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_barril_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barril',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='barril',
            name='estilo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.estilo'),
        ),
        migrations.AlterField(
            model_name='barril',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lote'),
        ),
        migrations.AlterField(
            model_name='barril',
            name='ubicacion',
            field=models.ForeignKey(blank=True, default='Fábrica', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cliente'),
        ),
    ]
