# Generated by Django 4.1.7 on 2023-03-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_barril_cliente_alter_barril_estilo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barril',
            name='ubicacion',
            field=models.ForeignKey(default='Fábrica', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cliente'),
        ),
    ]
