# Generated by Django 4.1.7 on 2023-03-29 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_barril_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarrilado',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lote'),
        ),
        migrations.AlterField(
            model_name='embarrilado',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cliente'),
        ),
    ]
